<?php

namespace PaynetEasy\PaynetEasyApi\PaymentData;

use Exception;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-06-25 at 18:19:35.
 */
class PaymentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Payment
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Payment;
    }

    public function testSerialize()
    {
        $this->object->setCustomer(new Customer(array
        (
            'first_name'    => 'Vasya',
            'last_name'     => 'Pupkin',
            'email'         => 'vass.pupkin@example.com',
        )));

        $this->object->addError(new Exception);
        $this->object->addError(new Exception);

        $this->object->setStatus(Payment::STATUS_APPROVED);

        $serialized = serialize($this->object);

        $this->assertEquals('C:44:"PaynetEasy\PaynetEasyApi\PaymentData\Payment":34:{a:1:{s:6:"status";s:8:"approved";}}', $serialized);
    }

    public function testUnserialize()
    {
        $payment = unserialize('C:44:"PaynetEasy\PaynetEasyApi\PaymentData\Payment":34:{a:1:{s:6:"status";s:8:"approved";}}');

        $this->assertEquals(Payment::STATUS_APPROVED, $payment->getStatus());
    }
}
